CREATE TABLE IF NOT EXISTS countries (
  country_code CHAR(2) NOT NULL,
  country_name VARCHAR(100) NOT NULL,
  currency_code CHAR(3) NOT NULL,
  currency_name VARCHAR(80) NOT NULL,
  currency_symbol VARCHAR(12) NOT NULL DEFAULT '',
  PRIMARY KEY (country_code),
  KEY idx_currency_code (currency_code),
  KEY idx_country_name (country_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO countries (country_code,country_name,currency_code,currency_name,currency_symbol) VALUES
('AW','Aruba','AWG','Aruban florin','ƒ'),
('AF','Afghanistan','AFN','Afghan afghani','؋'),
('AO','Angola','AOA','Angolan kwanza','Kz'),
('AI','Anguilla','XCD','Eastern Caribbean dollar','$'),
('AX','Åland Islands','EUR','Euro','€'),
('AL','Albania','ALL','Albanian lek','L'),
('AD','Andorra','EUR','Euro','€'),
('AE','United Arab Emirates','AED','United Arab Emirates dirham','د.إ'),
('AR','Argentina','ARS','Argentine peso','$'),
('AM','Armenia','AMD','Armenian dram','֏'),
('AS','American Samoa','USD','United States dollar','$'),
('AQ','Antarctica','USD','US Dollar','$'),
('TF','French Southern and Antarctic Lands','EUR','Euro','€'),
('AG','Antigua and Barbuda','XCD','Eastern Caribbean dollar','$'),
('AU','Australia','AUD','Australian dollar','$'),
('AT','Austria','EUR','Euro','€'),
('AZ','Azerbaijan','AZN','Azerbaijani manat','₼'),
('BI','Burundi','BIF','Burundian franc','Fr'),
('BE','Belgium','EUR','Euro','€'),
('BJ','Benin','XOF','West African CFA franc','Fr'),
('BF','Burkina Faso','XOF','West African CFA franc','Fr'),
('BD','Bangladesh','BDT','Bangladeshi taka','৳'),
('BG','Bulgaria','BGN','Bulgarian lev','лв'),
('BH','Bahrain','BHD','Bahraini dinar','.د.ب'),
('BS','Bahamas','BSD','Bahamian dollar','$'),
('BA','Bosnia and Herzegovina','BAM','Bosnia and Herzegovina convertible mark','KM'),
('BL','Saint Barthélemy','EUR','Euro','€'),
('SH','Saint Helena, Ascension and Tristan da Cunha','GBP','Pound sterling','£'),
('BY','Belarus','BYN','Belarusian ruble','Br'),
('BZ','Belize','BZD','Belize dollar','$'),
('BM','Bermuda','BMD','Bermudian dollar','$'),
('BO','Bolivia','BOB','Bolivian boliviano','Bs.'),
('BQ','Caribbean Netherlands','USD','United States dollar','$'),
('BR','Brazil','BRL','Brazilian real','R$'),
('BB','Barbados','BBD','Barbadian dollar','$'),
('BN','Brunei','BND','Brunei dollar','$'),
('BT','Bhutan','BTN','Bhutanese ngultrum','Nu.'),
('BV','Bouvet Island','USD','US Dollar','$'),
('BW','Botswana','BWP','Botswana pula','P'),
('CF','Central African Republic','XAF','Central African CFA franc','Fr'),
('CA','Canada','CAD','Canadian dollar','$'),
('CC','Cocos (Keeling) Islands','AUD','Australian dollar','$'),
('CH','Switzerland','CHF','Swiss franc','Fr.'),
('CL','Chile','CLP','Chilean peso','$'),
('CN','China','CNY','Chinese yuan','¥'),
('CI','Ivory Coast','XOF','West African CFA franc','Fr'),
('CM','Cameroon','XAF','Central African CFA franc','Fr'),
('CD','DR Congo','CDF','Congolese franc','FC'),
('CG','Congo','XAF','Central African CFA franc','Fr'),
('CK','Cook Islands','CKD','Cook Islands dollar','$'),
('CO','Colombia','COP','Colombian peso','$'),
('KM','Comoros','KMF','Comorian franc','Fr'),
('CV','Cape Verde','CVE','Cape Verdean escudo','Esc'),
('CR','Costa Rica','CRC','Costa Rican colón','₡'),
('CU','Cuba','CUC','Cuban convertible peso','$'),
('CW','Curaçao','ANG','Netherlands Antillean guilder','ƒ'),
('CX','Christmas Island','AUD','Australian dollar','$'),
('KY','Cayman Islands','KYD','Cayman Islands dollar','$'),
('CY','Cyprus','EUR','Euro','€'),
('CZ','Czechia','CZK','Czech koruna','Kč'),
('DE','Germany','EUR','Euro','€'),
('DJ','Djibouti','DJF','Djiboutian franc','Fr'),
('DM','Dominica','XCD','Eastern Caribbean dollar','$'),
('DK','Denmark','DKK','Danish krone','kr'),
('DO','Dominican Republic','DOP','Dominican peso','$'),
('DZ','Algeria','DZD','Algerian dinar','د.ج'),
('EC','Ecuador','USD','United States dollar','$'),
('EG','Egypt','EGP','Egyptian pound','£'),
('ER','Eritrea','ERN','Eritrean nakfa','Nfk'),
('EH','Western Sahara','DZD','Algerian dinar','دج'),
('ES','Spain','EUR','Euro','€'),
('EE','Estonia','EUR','Euro','€'),
('ET','Ethiopia','ETB','Ethiopian birr','Br'),
('FI','Finland','EUR','Euro','€'),
('FJ','Fiji','FJD','Fijian dollar','$'),
('FK','Falkland Islands','FKP','Falkland Islands pound','£'),
('FR','France','EUR','Euro','€'),
('FO','Faroe Islands','DKK','Danish krone','kr'),
('FM','Micronesia','USD','US Dollar','$'),
('GA','Gabon','XAF','Central African CFA franc','Fr'),
('GB','United Kingdom','GBP','British pound','£'),
('GE','Georgia','GEL','lari','₾'),
('GG','Guernsey','GBP','British pound','£'),
('GH','Ghana','GHS','Ghanaian cedi','₵'),
('GI','Gibraltar','GIP','Gibraltar pound','£'),
('GN','Guinea','GNF','Guinean franc','Fr'),
('GP','Guadeloupe','EUR','Euro','€'),
('GM','Gambia','GMD','dalasi','D'),
('GW','Guinea-Bissau','XOF','West African CFA franc','Fr'),
('GQ','Equatorial Guinea','XAF','Central African CFA franc','Fr'),
('GR','Greece','EUR','Euro','€'),
('GD','Grenada','XCD','Eastern Caribbean dollar','$'),
('GL','Greenland','DKK','krone','kr.'),
('GT','Guatemala','GTQ','Guatemalan quetzal','Q'),
('GF','French Guiana','EUR','Euro','€'),
('GU','Guam','USD','United States dollar','$'),
('GY','Guyana','GYD','Guyanese dollar','$'),
('HK','Hong Kong','HKD','Hong Kong dollar','$'),
('HM','Heard Island and McDonald Islands','USD','US Dollar','$'),
('HN','Honduras','HNL','Honduran lempira','L'),
('HR','Croatia','EUR','Euro','€'),
('HT','Haiti','HTG','Haitian gourde','G'),
('HU','Hungary','HUF','Hungarian forint','Ft'),
('ID','Indonesia','IDR','Indonesian rupiah','Rp'),
('IM','Isle of Man','GBP','British pound','£'),
('IN','India','INR','Indian rupee','₹'),
('IO','British Indian Ocean Territory','USD','United States dollar','$'),
('IE','Ireland','EUR','Euro','€'),
('IR','Iran','IRR','Iranian rial','﷼'),
('IQ','Iraq','IQD','Iraqi dinar','ع.د'),
('IS','Iceland','ISK','Icelandic króna','kr'),
('IL','Israel','ILS','Israeli new shekel','₪'),
('IT','Italy','EUR','Euro','€'),
('JM','Jamaica','JMD','Jamaican dollar','$'),
('JE','Jersey','GBP','British pound','£'),
('JO','Jordan','JOD','Jordanian dinar','د.ا'),
('JP','Japan','JPY','Japanese yen','¥'),
('KZ','Kazakhstan','KZT','Kazakhstani tenge','₸'),
('KE','Kenya','KES','Kenyan shilling','Sh'),
('KG','Kyrgyzstan','KGS','Kyrgyzstani som','с'),
('KH','Cambodia','KHR','Cambodian riel','៛'),
('KI','Kiribati','AUD','Australian dollar','$'),
('KN','Saint Kitts and Nevis','XCD','Eastern Caribbean dollar','$'),
('KR','South Korea','KRW','South Korean won','₩'),
('XK','Kosovo','EUR','Euro','€'),
('KW','Kuwait','KWD','Kuwaiti dinar','د.ك'),
('LA','Laos','LAK','Lao kip','₭'),
('LB','Lebanon','LBP','Lebanese pound','ل.ل'),
('LR','Liberia','LRD','Liberian dollar','$'),
('LY','Libya','LYD','Libyan dinar','ل.د'),
('LC','Saint Lucia','XCD','Eastern Caribbean dollar','$'),
('LI','Liechtenstein','CHF','Swiss franc','Fr'),
('LK','Sri Lanka','LKR','Sri Lankan rupee','Rs රු'),
('LS','Lesotho','LSL','Lesotho loti','L'),
('LT','Lithuania','EUR','Euro','€'),
('LU','Luxembourg','EUR','Euro','€'),
('LV','Latvia','EUR','Euro','€'),
('MO','Macau','MOP','Macanese pataca','P'),
('MF','Saint Martin','EUR','Euro','€'),
('MA','Morocco','MAD','Moroccan dirham','د.م.'),
('MC','Monaco','EUR','Euro','€'),
('MD','Moldova','MDL','Moldovan leu','L'),
('MG','Madagascar','MGA','Malagasy ariary','Ar'),
('MV','Maldives','MVR','Maldivian rufiyaa','.ރ'),
('MX','Mexico','MXN','Mexican peso','$'),
('MH','Marshall Islands','USD','United States dollar','$'),
('MK','North Macedonia','MKD','denar','den'),
('ML','Mali','XOF','West African CFA franc','Fr'),
('MT','Malta','EUR','Euro','€'),
('MM','Myanmar','MMK','Burmese kyat','Ks'),
('ME','Montenegro','EUR','Euro','€'),
('MN','Mongolia','MNT','Mongolian tögrög','₮'),
('MP','Northern Mariana Islands','USD','United States dollar','$'),
('MZ','Mozambique','MZN','Mozambican metical','MT'),
('MR','Mauritania','MRU','Mauritanian ouguiya','UM'),
('MS','Montserrat','XCD','Eastern Caribbean dollar','$'),
('MQ','Martinique','EUR','Euro','€'),
('MU','Mauritius','MUR','Mauritian rupee','₨'),
('MW','Malawi','MWK','Malawian kwacha','MK'),
('MY','Malaysia','MYR','Malaysian ringgit','RM'),
('YT','Mayotte','EUR','Euro','€'),
('NA','Namibia','NAD','Namibian dollar','$'),
('NC','New Caledonia','XPF','CFP franc','₣'),
('NE','Niger','XOF','West African CFA franc','Fr'),
('NF','Norfolk Island','AUD','Australian dollar','$'),
('NG','Nigeria','NGN','Nigerian naira','₦'),
('NI','Nicaragua','NIO','Nicaraguan córdoba','C$'),
('NU','Niue','NZD','New Zealand dollar','$'),
('NL','Netherlands','EUR','Euro','€'),
('NO','Norway','NOK','Norwegian krone','kr'),
('NP','Nepal','NPR','Nepalese rupee','₨'),
('NR','Nauru','AUD','Australian dollar','$'),
('NZ','New Zealand','NZD','New Zealand dollar','$'),
('OM','Oman','OMR','Omani rial','ر.ع.'),
('PK','Pakistan','PKR','Pakistani rupee','₨'),
('PA','Panama','PAB','Panamanian balboa','B/.'),
('PN','Pitcairn Islands','NZD','New Zealand dollar','$'),
('PE','Peru','PEN','Peruvian sol','S/.'),
('PH','Philippines','PHP','Philippine peso','₱'),
('PW','Palau','USD','United States dollar','$'),
('PG','Papua New Guinea','PGK','Papua New Guinean kina','K'),
('PL','Poland','PLN','Polish złoty','zł'),
('PR','Puerto Rico','USD','United States dollar','$'),
('KP','North Korea','KPW','North Korean won','₩'),
('PT','Portugal','EUR','Euro','€'),
('PY','Paraguay','PYG','Paraguayan guaraní','₲'),
('PS','Palestine','EGP','Egyptian pound','E£'),
('PF','French Polynesia','XPF','CFP franc','₣'),
('QA','Qatar','QAR','Qatari riyal','ر.ق'),
('RE','Réunion','EUR','Euro','€'),
('RO','Romania','RON','Romanian leu','lei'),
('RU','Russia','RUB','Russian ruble','₽'),
('RW','Rwanda','RWF','Rwandan franc','Fr'),
('SA','Saudi Arabia','SAR','Saudi riyal','ر.س'),
('SD','Sudan','SDG','Sudanese pound','PT'),
('SN','Senegal','XOF','West African CFA franc','Fr'),
('SG','Singapore','SGD','Singapore dollar','$'),
('GS','South Georgia','SHP','Saint Helena pound','£'),
('SJ','Svalbard and Jan Mayen','NOK','krone','kr'),
('SB','Solomon Islands','SBD','Solomon Islands dollar','$'),
('SL','Sierra Leone','SLL','Sierra Leonean leone','Le'),
('SV','El Salvador','USD','United States dollar','$'),
('SM','San Marino','EUR','Euro','€'),
('SO','Somalia','SOS','Somali shilling','Sh'),
('PM','Saint Pierre and Miquelon','EUR','Euro','€'),
('RS','Serbia','RSD','Serbian dinar','дин.'),
('SS','South Sudan','SSP','South Sudanese pound','£'),
('ST','São Tomé and Príncipe','STN','São Tomé and Príncipe dobra','Db'),
('SR','Suriname','SRD','Surinamese dollar','$'),
('SK','Slovakia','EUR','Euro','€'),
('SI','Slovenia','EUR','Euro','€'),
('SE','Sweden','SEK','Swedish krona','kr'),
('SZ','Eswatini','SZL','Swazi lilangeni','L'),
('SX','Sint Maarten','ANG','Netherlands Antillean guilder','ƒ'),
('SC','Seychelles','SCR','Seychellois rupee','₨'),
('SY','Syria','SYP','Syrian pound','£'),
('TC','Turks and Caicos Islands','USD','United States dollar','$'),
('TD','Chad','XAF','Central African CFA franc','Fr'),
('TG','Togo','XOF','West African CFA franc','Fr'),
('TH','Thailand','THB','Thai baht','฿'),
('TJ','Tajikistan','TJS','Tajikistani somoni','ЅМ'),
('TK','Tokelau','NZD','New Zealand dollar','$'),
('TM','Turkmenistan','TMT','Turkmenistan manat','m'),
('TL','Timor-Leste','USD','United States dollar','$'),
('TO','Tonga','TOP','Tongan paʻanga','T$'),
('TT','Trinidad and Tobago','TTD','Trinidad and Tobago dollar','$'),
('TN','Tunisia','TND','Tunisian dinar','د.ت'),
('TR','Türkiye','TRY','Turkish lira','₺'),
('TV','Tuvalu','AUD','Australian dollar','$'),
('TW','Taiwan','TWD','New Taiwan dollar','$'),
('TZ','Tanzania','TZS','Tanzanian shilling','Sh'),
('UG','Uganda','UGX','Ugandan shilling','Sh'),
('UA','Ukraine','UAH','Ukrainian hryvnia','₴'),
('UM','United States Minor Outlying Islands','USD','United States dollar','$'),
('UY','Uruguay','UYU','Uruguayan peso','$'),
('US','United States','USD','United States dollar','$'),
('UZ','Uzbekistan','UZS','Uzbekistani soʻm','so\'m'),
('VA','Vatican City','EUR','Euro','€'),
('VC','Saint Vincent and the Grenadines','XCD','Eastern Caribbean dollar','$'),
('VE','Venezuela','VES','Venezuelan bolívar soberano','Bs.S.'),
('VG','British Virgin Islands','USD','United States dollar','$'),
('VI','United States Virgin Islands','USD','United States dollar','$'),
('VN','Vietnam','VND','Vietnamese đồng','₫'),
('VU','Vanuatu','VUV','Vanuatu vatu','Vt'),
('WF','Wallis and Futuna','XPF','CFP franc','₣'),
('WS','Samoa','WST','Samoan tālā','T'),
('YE','Yemen','YER','Yemeni rial','﷼'),
('ZA','South Africa','ZAR','South African rand','R'),
('ZM','Zambia','ZMW','Zambian kwacha','ZK'),
('ZW','Zimbabwe','BWP','Botswana pula','P')
ON DUPLICATE KEY UPDATE country_name=VALUES(country_name), currency_code=VALUES(currency_code), currency_name=VALUES(currency_name), currency_symbol=VALUES(currency_symbol);